secultce/mapasculturais-v5

.gitmodules
dev-scripts/docker-compose.local.yml

Setando tema ceara e add plugin de recurso no gitmodulo

:wrench: Add tema pelo docker compose e gitmodule

---

.gitignore
.gitmodules

Adicionado dentro do submodulo do git o tema Ceara

🔔 Adicionando tema Ceara

---

.github/workflows/ci.yml
Dockerfile
README.md
compose/common/config.d/0.main.php
compose/common/config.d/maps.php
compose/common/config.d/plugins.php
compose/common/config.php
compose/production/config.d/authentication.php

Atualização do dockerfile de produção
Atualização do ci.yml
Ajustes nos arquivos de configuração da pasta compose

Atualização dos arquivos de configuração para produção.

---

.github/workflows/ci.yml

Atualiza ci.yml para criar imagem de produção após pull request na banch homolog

Atualiza ci.yml 

---

.github/workflows/ci.yml
.gitmodules
README.md
compose/local/config.d/plugins.php
db/dump.sql
dev-scripts/docker-compose.local.yml

Atualiza ci.yml para delploy no servidor de homologação

Atualização Github Actions

---

.github/workflows/ci.yml

Merge infra to Develop

---

.github/workflows/ci.yml
.gitmodules
compose/local/config.d/plugins.php
db/dump.sql
dev-scripts/docker-compose.local.yml

- add novos repositórios em gitmodules
- Arquivo de C.I para GitHubActions
- Add plugin do Parecer

Merge develop to Main

---

.gitignore
.gitmodules

Add modulo de diligencia no gitignore e removido plugin do submodulo

:see_no_evil: Up gitignore e gitmodules

---

src/protected/application/lib/MapasCulturais/ApiOutputs/Json.php

Previne exeder o limite de memória no endpoint de busca de Agentes

---

src/protected/application/lib/modules/Diligence/Entities/AnswerDiligence.php
src/protected/application/lib/modules/Diligence/Entities/Diligence.php
src/protected/application/lib/modules/Diligence/assets/js/diligence/proponent.js
src/protected/application/lib/modules/Diligence/layouts/parts/diligence/days.php

Foi criado um modulo de diligência para ser usado de uma maneira que somente terá uma interação entre o avaliador e o proponente

Modulo de Diligência

---

Dockerfile

Adicionado extensão no Dockerfile para o sockets, que será usado pelo pacote do RabbitMQ

:rocket: Add extensão sockets

---

src/protected/application/lib/modules/Diligence/Module.php
src/protected/application/lib/modules/Diligence/assets/css/diligence/form-config.css
src/protected/application/lib/modules/Diligence/assets/js/diligence/diligence-config-options.js
src/protected/application/lib/modules/Diligence/layouts/parts/opportunity/diligence-config-options.php

Remoção da edição do período de diligência após o envio da mesma

---

src/protected/application/lib/modules/Diligence/Controllers/Controller.php
src/protected/application/lib/modules/Diligence/Entities/Diligence.php
src/protected/application/lib/modules/Diligence/Module.php
src/protected/application/lib/modules/Diligence/assets/css/diligence/opportunity-diligence.css
src/protected/application/lib/modules/Diligence/assets/js/diligence/opportunity-diligence.js
src/protected/application/lib/modules/Diligence/layouts/parts/opportunity/diligence-content.php
src/protected/application/lib/modules/Diligence/layouts/parts/opportunity/tab-diligences.php

Adicionar status de diligência a Avaliação

---

src/protected/application/lib/MapasCulturais/Entities/File.php
src/protected/application/lib/modules/Diligence/Controllers/Controller.php
src/protected/application/lib/modules/Diligence/Entities/Diligence.php
src/protected/application/lib/modules/Diligence/Entities/DiligenceFile.php
src/protected/application/lib/modules/Diligence/Module.php
src/protected/application/lib/modules/Diligence/Repositories/Diligence.php
src/protected/application/lib/modules/Diligence/assets/js/diligence/proponent.js
src/protected/application/lib/modules/Diligence/layouts/parts/diligence/body-diligence-common.php
src/protected/application/lib/modules/Diligence/layouts/parts/diligence/body-proponent-common.php
src/protected/application/lib/modules/Diligence/layouts/parts/diligence/btn-actions-proponent.php

Anexos da diligência única

---

src/protected/application/lib/modules/Diligence/Module.php
src/protected/application/lib/modules/Reports/Module.php
src/protected/application/themes/BaseV1/views/opportunity/report-evaluations.php

Adicionado campo com valor do projeto a planilha de avaliações

---

dev-scripts/docker-compose.local.yml
src/protected/application/lib/modules/Diligence/Entities/Diligence.php

- Novas variáveis de ambiente para conexão com Rabbitmq
- Variáveis no Docker Compose
- Alterado no arquivo para a diligência

:wrench: Add variaveis de ambiente

---

src/protected/application/lib/MapasCulturais/Controllers/RegistrationsDraw.php
src/protected/application/lib/MapasCulturais/Entities/RegistrationsRanking.php
src/protected/application/lib/modules/RegistrationsDraw/Module.php
src/protected/application/lib/modules/RegistrationsDraw/assets/js/prize-draw-content.js
src/protected/application/lib/modules/RegistrationsDraw/layouts/parts/opportunity/prize-draw-content.php
src/protected/db-updates.php

Adicionando novos campos a tabela registrations_ranking

---

src/protected/application/lib/MapasCulturais/Controllers/RegistrationsDraw.php
src/protected/application/lib/MapasCulturais/Entities/RegistrationsRanking.php
src/protected/application/lib/modules/RegistrationsDraw/Module.php
src/protected/application/lib/modules/RegistrationsDraw/assets/css/prize-draw.css
src/protected/application/lib/modules/RegistrationsDraw/assets/js/prize-draw-content.js
src/protected/application/lib/modules/RegistrationsDraw/layouts/parts/opportunity/prize-draw-content.php
src/protected/composer.json
src/protected/db-updates.php

Criando XLSX

---

CHANGELOG.md
src/protected/application/lib/MapasCulturais/Controllers/RegistrationsDraw.php
src/protected/application/lib/modules/RegistrationsDraw/Module.php
src/protected/application/lib/modules/RegistrationsDraw/assets/css/prize-draw.css
src/protected/application/lib/modules/RegistrationsDraw/assets/js/prize-draw-content.js
src/protected/application/lib/modules/RegistrationsDraw/layouts/parts/opportunity/prize-draw-content.php

Criar aba de sorteio para proponente ou visitante para visualizar o resultado do sorteio

---

src/protected/application/lib/MapasCulturais/Controllers/RegistrationsDraw.php

Melhorando fluxo de decisão nas respostas do endpoint

---

README.md

Alterando o readme para o contexto atual da equipe
#86 
---
---
---
---

:globe_with_meridians: #86 - Alterado o Readme

---

src/protected/application/lib/modules/Diligence/Entities/AnswerDiligence.php
src/protected/application/lib/modules/Diligence/Entities/Diligence.php
src/protected/application/lib/modules/Diligence/Module.php
src/protected/application/lib/modules/Diligence/layouts/parts/diligence/proponent.php
src/protected/application/lib/modules/Diligence/layouts/parts/opportunity/diligence-config-options.php

Tipo de dia para resposta da diligência

---

.gitmodules
compose/common/config.d/plugins.php
compose/local/config.d/plugins.php

Adicionando plugin BigSheetImporter

---

compose/common/config.d/plugins.php
compose/local/config.d/plugins.php

Atualizando plugins

---

compose/common/config.d/plugins.php
compose/local/config.d/plugins.php
dev-scripts/docker-compose.local.yml

Referência para o plugin BigSheetImporter

---

src/protected/application/lib/modules/Diligence/Entities/Diligence.php

add o doctrine para mapeamento da tabela de diligencia
Adicionar Doctrine na classe de Diligencia
#212 
---
---
---
---

:bug: #212 - Add ORM Doctrine

---

src/protected/application/lib/MapasCulturais/Entities/EntityRevision.php
src/protected/application/lib/MapasCulturais/Entities/Opportunity.php
src/protected/application/lib/MapasCulturais/Traits/EntityRevision.php
src/protected/application/lib/modules/Diligence/Module.php
src/protected/application/themes/BaseV1/layouts/parts/singles/opportunity-about.php
src/protected/application/themes/BaseV1/layouts/parts/singles/opportunity/quota-config.php

Configuração de vagas para cotistas na oportunidade

---

dev-scripts/docker-compose.local.yml
src/protected/application/lib/MapasCulturais/Utils.php
src/protected/application/themes/BaseV1/layouts/parts/singles/opportunity/quota-config.php

Habilitar config de cotas somente para agentes com selo

---

src/protected/application/lib/MapasCulturais/Utils.php

Verificando se tem objeto usuario se nao é um array vazio
Validando usuário
#230 
---
---
---
---

:bug: #230 - Verificação de usuario

---

src/protected/application/lib/modules/Diligence/Entities/Diligence.php
src/protected/application/lib/modules/Diligence/assets/js/diligence/diligence.js

Removendo mensagem de assunto quando for diligência única
Corrigir mensagem de erro de assunto quando for diligência única
#232 
---
---
---
---

:bug: #232 - Removendo mensagem de assunto

---

src/protected/application/lib/modules/Diligence/Controllers/Controller.php
src/protected/application/lib/modules/Diligence/Controllers/Tado.php
src/protected/application/lib/modules/Diligence/Entities/NotificationDiligence.php
src/protected/application/lib/modules/Diligence/Module.php
src/protected/application/lib/modules/Diligence/layouts/parts/multi/accountability-actions.php
src/protected/application/lib/modules/Diligence/layouts/parts/multi/multi-select.php
src/protected/application/lib/modules/Diligence/layouts/parts/multi/report-tado.php

Gerando tado para o proponente e notificando o mesmo
#224 
---
---
---
---

✨ Tado ao proponente

---

src/protected/application/lib/modules/Diligence/assets/js/diligence/diligence.js

Verificando o tipo de diligencia para alterar o assunto
Verificar qual é o tipo de diligência para tratar o assunto
#240 
---
---
---
---

:technologist: #240 - Validadndo multipla diligencia

---

src/protected/application/lib/MapasCulturais/App.php
src/protected/application/lib/MapasCulturais/DoctrineMappings/Functions/RegexpReplace.php
src/protected/application/lib/modules/QuotasSet/Module.php

Adiciona função regexp_replace ao mapping do Doctrine

---

src/protected/application/lib/modules/Diligence/Repositories/Diligence.php
src/protected/application/lib/modules/Diligence/assets/js/multi/multi.js

Verificado o retorno que ocasionado o erro e corrigido
Verificação de um retorno na consulta do banco e devolvendo para o frontEnd
#259 
---
---
---
---

:bug: #259 - Removendo mensagem de erro dos logs

---

src/protected/application/lib/modules/Diligence/Controllers/Controller.php
src/protected/application/lib/modules/Diligence/Controllers/Refo.php
src/protected/application/lib/modules/Diligence/Controllers/Tado.php
src/protected/application/lib/modules/Diligence/Module.php
src/protected/application/lib/modules/Diligence/Repositories/Diligence.php
src/protected/application/lib/modules/Diligence/assets/css/diligence/style.css
src/protected/application/lib/modules/Diligence/assets/js/diligence/diligence.js
src/protected/application/lib/modules/Diligence/assets/js/diligence/diligenceMessage.js
src/protected/application/lib/modules/Diligence/assets/js/diligence/proponent.js
src/protected/application/lib/modules/Diligence/layouts/parts/diligence/body-diligence-multi.php
src/protected/application/lib/modules/Diligence/layouts/parts/diligence/body-diligence-subject.php
src/protected/application/lib/modules/Diligence/layouts/parts/diligence/edit-description.php
src/protected/application/lib/modules/Diligence/layouts/parts/diligence/proponent.php
src/protected/application/lib/modules/Diligence/layouts/parts/diligence/tabs-parent.php

Adicionando funcionalidade de excluir rascunhos

---

src/protected/application/lib/MapasCulturais/ApiQuery.php
src/protected/application/lib/MapasCulturais/Controllers/Opportunity.php

Reordenando a lista de inscritos por nota
---
---
---
---
---

:children_crossing: #202 - Lista de inscritos por nota desc.

---

compose/common/config.d/plugins.php
compose/local/config.d/plugins.php

Ativar plugin de acessibilidade

---

Dockerfile
compose/local/Dockerfile

fix: Corrige versão do php-redis a ser instalado

---

compose/production/config.d/auth.php

:technologist: #278 - Habilitado confirmação de email

---

Dockerfile

:rocket: #281 - Add composer update

---

Dockerfile
compose/production/config.d/auth.php

✅  Merge develop to homolog

---

src/protected/application/lib/MapasCulturais/Controllers/EntityRevision.php

Proibindo acesso de visitante ao historico de entidades
---
---
---
---
---

🕙 Histórico de entidades

---

src/protected/application/lib/modules/OpportunityPhases/Module.php
src/protected/db-updates.php

Add limite de fases com base no banco de dados.
---
---
---
---
---

✨ Add limite de fases

---

src/protected/application/lib/MapasCulturais/ApiQuery.php

Ajuste listagem de inscrições em rascunho

---

src/protected/application/themes/BaseV1/views/panel/registrations.php

Algumas inscrições não exibidas em 'minhas inscrições'

---

src/protected/application/themes/BaseV1/layouts/parts/singles/opportunity-registrations--tables--manager.php
src/protected/application/themes/BaseV1/layouts/parts/singles/opportunity-registrations--tables--published.php

Atualizando o informativo de quantidade de inscrições
---
---
---
---
---

:children_crossing: Mostrando as inscrições

---

src/protected/application/lib/modules/Charts/layouts/parts/charts/line.php

Atualização da develop
---
---
---
---
---

:bug: #316 - Add indice no array

---

CHANGELOG.md

:bookmark: Alterando changelog

---

CHANGELOG.md

:bookmark: Removendo plugin

---

src/protected/application/lib/MapasCulturais/ApiQuery.php
src/protected/application/lib/MapasCulturais/Controllers/Opportunity.php
src/protected/application/themes/BaseV1/layouts/parts/singles/opportunity-evaluations--admin--table.php
src/protected/application/themes/BaseV1/layouts/parts/singles/opportunity-evaluations--committee--table.php

Correção na listagem de avaliações

---

src/protected/application/lib/MapasCulturais/Utils.php

 Tratando existência do getMetadata ao usar getTermsByOpportunity

---

compose/production/config.d/auth.php

Atualizações da develop para homologação
---
---
---
---
---

Merge develop to homolog

---

src/protected/application/lib/modules/Diligence/Repositories/Diligence.php
src/protected/application/lib/modules/Diligence/layouts/parts/diligence/body-diligence-multi.php
src/protected/application/themes/BaseV1/layouts/parts/singles/opportunity-evaluations--committee--table.php

Filtrando a diligência para ser acessada somente por um fiscal que já teve a diligência
#344 
---
---
---
---

🐛 #344 - Filtrando fiscal por diligencia

---

src/protected/application/lib/modules/Diligence/assets/css/diligence/style.css
src/protected/application/lib/modules/Diligence/assets/js/diligence/entity-diligence.js
src/protected/application/lib/modules/Diligence/assets/js/diligence/proponent.js
src/protected/application/lib/modules/Diligence/layouts/parts/diligence/body-diligence-multi.php
src/protected/application/lib/modules/Diligence/layouts/parts/diligence/proponent.php
src/protected/application/lib/modules/Diligence/layouts/parts/diligence/tabs-parent.php
src/protected/application/lib/modules/Diligence/layouts/parts/diligence/ul-buttons.php
src/protected/application/themes/BaseV1/views/registration/single.php

Redirecionamento de abas

---

src/protected/application/lib/modules/Diligence/Controllers/Controller.php
src/protected/application/lib/modules/Diligence/assets/css/diligence/style.css
src/protected/application/lib/modules/Diligence/layouts/parts/diligence/btn-actions-proponent.php
src/protected/application/lib/modules/Diligence/layouts/parts/diligence/description.php
src/protected/application/lib/modules/Diligence/layouts/parts/diligence/proponent.php
src/protected/application/lib/modules/Diligence/layouts/parts/diligence/tabs-parent.php

Salvando dados automáticamente
#334 
---
---
---
---

♻️ #334 - Rafatorando para salvar mensagem automáticamente

---

src/protected/application/lib/modules/Diligence/Controllers/Controller.php
src/protected/application/lib/modules/Diligence/Controllers/Tado.php
src/protected/application/lib/modules/Diligence/Entities/AnswerDiligence.php
src/protected/application/lib/modules/Diligence/Entities/Diligence.php
src/protected/application/lib/modules/Diligence/Entities/NotificationDiligence.php

Atualização de notificação aos fiscais.
#337 
---
---
---
---

🔔 Notificar Fiscais

---

src/protected/application/lib/modules/Diligence/assets/css/diligence/style.css
src/protected/application/lib/modules/Diligence/assets/js/multi/multi.js
src/protected/application/lib/modules/Diligence/layouts/parts/diligence/body-diligence-multi.php
src/protected/application/lib/modules/Diligence/layouts/parts/multi/multi-select.php

Criado novo status para adicionar arquivos
Adicionado novo status na diligência
#340 
---
---
---
---

💄 #340 - Adicionado status em análise

---

src/protected/application/lib/MapasCulturais/Utils.php
src/protected/application/lib/modules/Diligence/Controllers/Tado.php
src/protected/application/lib/modules/Diligence/Repositories/Diligence.php
src/protected/application/lib/modules/Diligence/assets/js/diligence/diligence.js
src/protected/application/lib/modules/Diligence/assets/js/diligence/entity-diligence.js
src/protected/application/lib/modules/Diligence/assets/js/diligence/proponent.js
src/protected/application/lib/modules/Diligence/layouts/parts/diligence/body-diligence-multi.php
src/protected/application/lib/modules/Diligence/layouts/parts/diligence/btn-actions-proponent.php
src/protected/application/lib/modules/Diligence/layouts/parts/diligence/description.php

Ajustes na Prestação de Contas

---

src/protected/application/lib/modules/Diligence/Controllers/Controller.php

♻️ Alterando logica para fiscais

---

src/protected/application/conf/conf-base.d/lgpd.php

Ativar LGPD

---

src/protected/application/lib/MapasCulturais/Entities/Registration.php

Atualização da referência do plugin Recourse

---

src/protected/application/themes/BaseV1/assets/js/ng.entity.module.opportunity.js

Mostrando um alerta para o proponente quando o coletivo for obrigatório
#388 
---
---
---
---

🚸 #388 Mostrando aviso quando coletivo for obrigatorio

---

src/protected/application/lib/MapasCulturais/Entities/Opportunity.php
src/protected/application/themes/BaseV1/Theme.php

Corrigindo a contagem de inscrições
---
---
---
---
---

:technologist: #412 - Refaltorando e corrigido bug de contagem

---

src/protected/application/lib/modules/CompliantSuggestion/Module.php
src/protected/application/lib/modules/CompliantSuggestion/assets/js/ng.modules.compliantSuggestion.js
src/protected/application/lib/modules/CompliantSuggestion/layouts/parts/compliant_suggestion.php

ReCAPTCHA v3 nos forms de contato

---

src/protected/application/lib/MapasCulturais/DoctrineEnumTypes/ObjectType.php
src/protected/application/lib/MapasCulturais/Entities/EntityRevision.php
src/protected/application/lib/MapasCulturais/Entities/RegistrationFieldConfiguration.php
src/protected/application/lib/MapasCulturais/Entities/RegistrationFileConfiguration.php
src/protected/application/lib/MapasCulturais/Traits/EntityRevision.php
src/protected/application/themes/BaseV1/Theme.php

Logs na construção dos formulários

---

src/protected/application/lib/MapasCulturais/ApiQuery.php

Retornar eventos desativados (endpoint get events - api)

---

src/protected/application/lib/modules/Diligence/Controllers/Controller.php
src/protected/application/lib/modules/Diligence/Entities/AnswerDiligence.php
src/protected/application/lib/modules/Diligence/Repositories/Diligence.php
src/protected/application/lib/modules/Diligence/assets/js/diligence/proponent.js

Corrige erro ao cancelar envio resposta da diligência

---

src/protected/application/plugins/EvaluationMethodQualification/Plugin.php

Avaliação de habilitação documental sem obrigatoriedade de opções de inabilitado

---

src/protected/application/lib/modules/OpportunityPhases/layouts/parts/import-last-phase-button.php

Botão de importar inscrições de outra fase

---

src/protected/application/lib/MapasCulturais/Entities/AgentRelation.php

Admin da oportunidade reabrir avaliações

---

src/protected/application/lib/modules/Diligence/layouts/parts/multi/report-tado.php
src/protected/application/lib/modules/Diligence/views/tado/emitir.php

Alterando nome do pdf e na página do TADO
---
---
---
---
---

🚸 #461 - Alterado para coordenador finalistico

---

src/protected/application/themes/BaseV1/views/pdf/footer-pdf.php

update PDF plugin reference

---

src/protected/application/lib/modules/QuotasSet/Module.php
src/protected/application/lib/modules/QuotasSet/layouts/parts/quotas-set-assign.tab.content.php
src/protected/application/lib/modules/QuotasSet/layouts/parts/registration/quotas-set.widget.unavailable.php

Adicionando exceções e mensagens de erro para serviço de cotas indisponível

---

src/protected/application/lib/MapasCulturais/Controllers/Registration.php
src/protected/application/lib/MapasCulturais/Entities/Registration.php

Mantendo o status de pendente para Exequibilidade Orçamentária
#483 
---
---
---
---

:recycle: #483 - Alterado para manter a inscricao como pendente

---

src/protected/application/lib/MapasCulturais/Controllers/EntityController.php
src/protected/application/lib/MapasCulturais/Traits/EntityArchive.php

Alterando o status da entidade
#492 
---
---
---
---

🔨 #492 - Criado método para disabilitar entidade

---

src/protected/application/lib/MapasCulturais/Controllers/Registration.php

Limpa campos condicionados não utilizados

---

CHANGELOG.md
compose/production/config.d/cache.php

🔨 Alterando o valor do cache do assets
---
---
---
---
---

🔨 Alterando o valor do cache do assets

---

src/protected/application/lib/modules/Diligence/Module.php

Adicionado arquivo proponent.js dentro da condição correta
#505 
---
---
---
---

🔨 #505 - Add arquivo dentro de uma logica

---

src/protected/application/lib/modules/Diligence/Controllers/Controller.php
src/protected/application/lib/modules/Diligence/Controllers/Tado.php
src/protected/application/lib/modules/Diligence/Entities/Diligence.php
src/protected/application/lib/modules/Diligence/Module.php
src/protected/application/lib/modules/Diligence/Repositories/Diligence.php
src/protected/application/lib/modules/Diligence/assets/css/diligence/opportunity-diligence.css
src/protected/application/lib/modules/Diligence/assets/js/diligence/opportunity-diligence.js
src/protected/application/lib/modules/Diligence/assets/js/diligence/proponent.js
src/protected/application/lib/modules/Diligence/layouts/parts/diligence/btn-actions-proponent.php
src/protected/application/lib/modules/Diligence/layouts/parts/opportunity/diligence-content.php
src/protected/application/lib/modules/Diligence/views/tado/emitir.php

feat: Adiciona status de "TADO gerado" a diligência

---

src/protected/application/lib/modules/Diligence/layouts/parts/opportunity/diligence-content.php

Corrige aba de diligência sempre visível

---

src/protected/application/lib/modules/Diligence/Controllers/Tado.php
src/protected/application/lib/modules/Diligence/assets/js/multi/tado.js
src/protected/application/lib/modules/Diligence/layouts/parts/multi/report-tado.php
src/protected/application/lib/modules/Diligence/views/tado/emitir.php

Correção na troca do nome do Fiscal para Coordenador.
---
---
---
---
---

🐛 #511 - Corrigido o troca do nome fiscal para coordenador

---

src/protected/application/lib/MapasCulturais/Controllers/Registration.php
src/protected/application/lib/MapasCulturais/Entities/Registration.php

Verificando campos obrigatórios quando for um checkbox
#527 
---
---
---
---

🐞 - Bugfix/field required

---

src/protected/application/lib/modules/Diligence/Module.php
src/protected/application/lib/modules/Diligence/layouts/parts/diligence/body-diligence-file-report.php
src/protected/application/lib/modules/Diligence/layouts/parts/diligence/btn-actions-proponent.php
src/protected/application/lib/modules/Diligence/layouts/parts/multi/accountability-actions.php
src/protected/application/lib/modules/Diligence/layouts/parts/multi/multi-select.php

Envio de arquivo pelo fiscal da prestação de contas

---

src/protected/application/lib/MapasCulturais/DoctrineEnumTypes/ObjectType.php
src/protected/application/lib/modules/Diligence/Controllers/Controller.php
src/protected/application/lib/modules/Diligence/Entities/Opinion.php
src/protected/application/lib/modules/Diligence/assets/css/diligence/multi.css
src/protected/application/lib/modules/Diligence/assets/css/diligence/style.css
src/protected/application/lib/modules/Diligence/assets/js/diligence/diligence.js
src/protected/application/lib/modules/Diligence/assets/js/diligence/entity-diligence.js
src/protected/application/lib/modules/Diligence/assets/js/diligence/proponent.js
src/protected/application/lib/modules/Diligence/assets/js/multi/multi.js
src/protected/application/lib/modules/Diligence/layouts/parts/diligence/tabs-parent.php
src/protected/application/lib/modules/Diligence/layouts/parts/diligence/ul-buttons.php
src/protected/application/lib/modules/Diligence/layouts/parts/multi/multi-select.php
src/protected/db-updates.php

Parecer da prestação de contas

---

dev-scripts/docker-compose.local.yml
src/protected/application/lib/MapasCulturais/Controllers/Registration.php
src/protected/application/lib/modules/RegistrationFieldTypes/layouts/parts/registration-field-types/fields/links.php
src/protected/application/themes/BaseV1/assets/js/ng.entity.module.opportunity.js

Limite no tamanho da requisição (inscrição)

---

dev-scripts/docker-compose.local.yml
dev-scripts/start-dev.sh
src/protected/application/conf/conf-base.d/rabbitmq.php
src/protected/application/lib/MapasCulturais/Services/AmqpQueueService.php
src/protected/application/lib/modules/OpportunityPhases/Module.php

Enviando dados para a mensageria 
#438 
---
---
---
---

[Draft] - 🔨 Emails para importação de inscritos em fases

---

src/protected/application/themes/BaseV1/views/pdf/footer-pdf.php

Ref. plugin PDFReport (imprimir inscrição de todas as fases)

---

compose/local/Dockerfile
src/protected/application/lib/modules/RegistrationFieldTypes/Module.php
src/protected/application/themes/BaseV1/assets/css/sass/components/_buttons.scss
src/protected/application/themes/BaseV1/assets/js/ng.entity.module.opportunity.js

Ajuste no unserialize dos campos do tipo checkboxes
